// flow-typed signature: 33d2168972e79a6540c180657c7d0972
// flow-typed version: <<STUB>>/react-sizeme_v^2.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sizeme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sizeme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sizeme/example/index' {
  declare module.exports: any;
}

declare module 'react-sizeme/example/server' {
  declare module.exports: any;
}

declare module 'react-sizeme/example/src/index' {
  declare module.exports: any;
}

declare module 'react-sizeme/example/src/MySizeAwareComponent' {
  declare module.exports: any;
}

declare module 'react-sizeme/example/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'react-sizeme/lib/react-sizeme' {
  declare module.exports: any;
}

declare module 'react-sizeme/src/resizeDetector' {
  declare module.exports: any;
}

declare module 'react-sizeme/src/sizeMe' {
  declare module.exports: any;
}

declare module 'react-sizeme/test/jsdom' {
  declare module.exports: any;
}

declare module 'react-sizeme/test/setup' {
  declare module.exports: any;
}

declare module 'react-sizeme/test/SizeMe.test' {
  declare module.exports: any;
}

declare module 'react-sizeme/wallaby.conf' {
  declare module.exports: any;
}

declare module 'react-sizeme/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sizeme/example/index.js' {
  declare module.exports: $Exports<'react-sizeme/example/index'>;
}
declare module 'react-sizeme/example/server.js' {
  declare module.exports: $Exports<'react-sizeme/example/server'>;
}
declare module 'react-sizeme/example/src/index.js' {
  declare module.exports: $Exports<'react-sizeme/example/src/index'>;
}
declare module 'react-sizeme/example/src/MySizeAwareComponent.js' {
  declare module.exports: $Exports<'react-sizeme/example/src/MySizeAwareComponent'>;
}
declare module 'react-sizeme/example/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-sizeme/example/webpack.config.babel'>;
}
declare module 'react-sizeme/lib/react-sizeme.js' {
  declare module.exports: $Exports<'react-sizeme/lib/react-sizeme'>;
}
declare module 'react-sizeme/src/resizeDetector.js' {
  declare module.exports: $Exports<'react-sizeme/src/resizeDetector'>;
}
declare module 'react-sizeme/src/sizeMe.js' {
  declare module.exports: $Exports<'react-sizeme/src/sizeMe'>;
}
declare module 'react-sizeme/test/jsdom.js' {
  declare module.exports: $Exports<'react-sizeme/test/jsdom'>;
}
declare module 'react-sizeme/test/setup.js' {
  declare module.exports: $Exports<'react-sizeme/test/setup'>;
}
declare module 'react-sizeme/test/SizeMe.test.js' {
  declare module.exports: $Exports<'react-sizeme/test/SizeMe.test'>;
}
declare module 'react-sizeme/wallaby.conf.js' {
  declare module.exports: $Exports<'react-sizeme/wallaby.conf'>;
}
declare module 'react-sizeme/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-sizeme/webpack.config.babel'>;
}
