// flow-typed signature: e1622e1c17f4cb7f4519de61ccb1bd89
// flow-typed version: <<STUB>>/react-component-queries_v^2.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-component-queries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-component-queries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-component-queries/lib/react-component-queries' {
  declare module.exports: any;
}

declare module 'react-component-queries/src/componentQueries' {
  declare module.exports: any;
}

declare module 'react-component-queries/src/index' {
  declare module.exports: any;
}

declare module 'react-component-queries/src/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-component-queries/src/utils/mergeWith' {
  declare module.exports: any;
}

declare module 'react-component-queries/src/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-component-queries/test/componentQueries.test' {
  declare module.exports: any;
}

declare module 'react-component-queries/test/jsdom' {
  declare module.exports: any;
}

declare module 'react-component-queries/test/setup' {
  declare module.exports: any;
}

declare module 'react-component-queries/wallaby.conf' {
  declare module.exports: any;
}

declare module 'react-component-queries/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-component-queries/lib/react-component-queries.js' {
  declare module.exports: $Exports<'react-component-queries/lib/react-component-queries'>;
}
declare module 'react-component-queries/src/componentQueries.js' {
  declare module.exports: $Exports<'react-component-queries/src/componentQueries'>;
}
declare module 'react-component-queries/src/index.js' {
  declare module.exports: $Exports<'react-component-queries/src/index'>;
}
declare module 'react-component-queries/src/utils/getDisplayName.js' {
  declare module.exports: $Exports<'react-component-queries/src/utils/getDisplayName'>;
}
declare module 'react-component-queries/src/utils/mergeWith.js' {
  declare module.exports: $Exports<'react-component-queries/src/utils/mergeWith'>;
}
declare module 'react-component-queries/src/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-component-queries/src/utils/shallowEqual'>;
}
declare module 'react-component-queries/test/componentQueries.test.js' {
  declare module.exports: $Exports<'react-component-queries/test/componentQueries.test'>;
}
declare module 'react-component-queries/test/jsdom.js' {
  declare module.exports: $Exports<'react-component-queries/test/jsdom'>;
}
declare module 'react-component-queries/test/setup.js' {
  declare module.exports: $Exports<'react-component-queries/test/setup'>;
}
declare module 'react-component-queries/wallaby.conf.js' {
  declare module.exports: $Exports<'react-component-queries/wallaby.conf'>;
}
declare module 'react-component-queries/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-component-queries/webpack.config.babel'>;
}
